export enum ProductActionTypes {
  GET_PRODUCT_LIST = "GET_PRODUCT_LIST",
  PUT_PENDING_PRODUCT_LIST = "PUT_PENDING_PRODUCT_LIST",
  PUT_ERROR_PRODUCT_LIST = "PUT_ERROR_PRODUCT_LIST",
  PUT_PRODUCT_LIST = "PUT_PRODUCT_LIST",
}
