export enum CartActions {
  ADD_ITEM = "ADD_ITEM",
  REMOVE_ITEM = "REMOVE_ITEM",
  REMOVE_ALL = "REMOVE_ALL",
  LOAD_CART = "LOAD_CART",
  ERROR_CART = "ERROR_CART",
  PENDING_CART = "PENDING_CART",
  ADD_ITEM_QUANTITY = "ADD_ITEM_QUANTITY",
  REDUCE_ITEM_QUANTITY = "REDUCE_ITEM_QUANTITY",
  CHANGE_ITEM_QUANTITY = "CHANGE_ITEM_QUANTITY",
}
