export enum CategoryActionTypes {
  GET_CATEGORY_LIST = "GET_CATEGORY_LIST",
  PUT_CATEGORY_LIST = "PUT_CATEGORY_LIST",
  ERROR_CATEGORY_LIST = "ERROR_CATEGORY_LIST",
  PENDING_CATEGORY_LIST = "PENDING_CATEGORY_LIST",
}
